USE [master]
GO

/****** Object:  Database [TDA_SARA]    Script Date: 01/03/2025 03:44:37 p. m. ******/
CREATE DATABASE [TDA_SARA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TDA_SARA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TDA_SARA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TDA_SARA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TDA_SARA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TDA_SARA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TDA_SARA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TDA_SARA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TDA_SARA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TDA_SARA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TDA_SARA] SET ARITHABORT OFF 
GO

ALTER DATABASE [TDA_SARA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TDA_SARA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TDA_SARA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TDA_SARA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TDA_SARA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TDA_SARA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TDA_SARA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TDA_SARA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TDA_SARA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TDA_SARA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TDA_SARA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TDA_SARA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TDA_SARA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TDA_SARA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TDA_SARA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TDA_SARA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TDA_SARA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TDA_SARA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TDA_SARA] SET  MULTI_USER 
GO

ALTER DATABASE [TDA_SARA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TDA_SARA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TDA_SARA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TDA_SARA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TDA_SARA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TDA_SARA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TDA_SARA] SET QUERY_STORE = ON
GO

ALTER DATABASE [TDA_SARA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TDA_SARA] SET  READ_WRITE 
GO

/******** Crear Tabla Carritos******/

USE [TDA_SARA]
GO

/****** Object:  Table [dbo].[Carrito]    Script Date: 01/03/2025 03:48:48 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Carrito](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FolioVta] [int] NOT NULL,
	[TotalCompra] [decimal](18, 0) NOT NULL,
	[Estatus] [int] NOT NULL,
	[Fecha] [date] NOT NULL,
 CONSTRAINT [PK_Carrito] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/******** Crear Tabla Carrito Detalle******/
USE [TDA_SARA]
GO

/****** Object:  Table [dbo].[CarDetalle]    Script Date: 01/03/2025 03:45:30 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CarDetalle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdCar] [int] NOT NULL,
	[IdProd] [int] NOT NULL,
	[Catidad] [int] NOT NULL,
	[Subtotal] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_CarDetalle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CarDetalle]  WITH CHECK ADD  CONSTRAINT [FK_CarDetalle_Carrito] FOREIGN KEY([IdCar])
REFERENCES [dbo].[Carrito] ([Id])
GO

ALTER TABLE [dbo].[CarDetalle] CHECK CONSTRAINT [FK_CarDetalle_Carrito]
GO

ALTER TABLE [dbo].[CarDetalle]  WITH CHECK ADD  CONSTRAINT [FK_CarDetalle_Productos] FOREIGN KEY([IdProd])
REFERENCES [dbo].[Productos] ([Id])
GO

ALTER TABLE [dbo].[CarDetalle] CHECK CONSTRAINT [FK_CarDetalle_Productos]
GO

/******** Crear Tabla Carrito Producto******/
USE [TDA_SARA]
GO

/****** Object:  Table [dbo].[Productos]    Script Date: 01/03/2025 03:49:51 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Productos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Categ] [int] NOT NULL,
	[Id_Marca] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Precio] [decimal](18, 0) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Categoria] FOREIGN KEY([Id_Categ])
REFERENCES [dbo].[Categoria] ([Id])
GO

ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Categoria]
GO

ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Marca] FOREIGN KEY([Id_Marca])
REFERENCES [dbo].[Marca] ([Id])
GO

ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Marca]
GO

/******** Crear Tabla Carrito Categoria******/
USE [TDA_SARA]
GO

/****** Object:  Table [dbo].[Categoria]    Script Date: 01/03/2025 03:50:38 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Categoria](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


/******** Crear Tabla Carrito Marca******/

USE [TDA_SARA]
GO

/****** Object:  Table [dbo].[Marca]    Script Date: 01/03/2025 03:51:54 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Marca](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Marca] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


/******Consulta de total de ventas agrupado por marca de producto. ******/

SELECT
    m.Descripcion AS NombreMarca,
    '$' + CAST(SUM(cd.Subtotal) AS VARCHAR) AS TotalVentasMarca
FROM
    CarDetalle cd
JOIN
    Productos p ON cd.IdProd = p.Id
JOIN
    Marca m ON p.Id_Marca = m.Id
GROUP BY
    m.Descripcion
ORDER BY
    TotalVentasMarca DESC;

/******Consulta de total de ventas agrupado por Categoria del producto. ******/
SELECT
    cat.Descripcion AS NombreCategoria,
    '$' + CAST(SUM(cd.Subtotal) AS VARCHAR) AS TotalVentasCategoria
FROM
    CarDetalle cd
JOIN
    Productos p ON cd.IdProd = p.Id
JOIN
    Categoria cat ON p.Id_Categ = cat.Id
GROUP BY
    cat.Descripcion
ORDER BY
    TotalVentasCategoria DESC;

/******Consulta de total de ventas agrupado por producto. ******/

	SELECT
    p.Descripcion AS NombreProducto,
    SUM(cd.Catidad) AS CantidadTotalVendida,
    '$' + CAST(SUM(cd.Subtotal) AS VARCHAR) AS SubtotalTotalVendido
FROM
    CarDetalle cd
JOIN
    Productos p ON cd.IdProd = p.Id
GROUP BY
    p.Descripcion
ORDER BY
    CantidadTotalVendida DESC;